name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: read

    outputs:
      head_commit_message: ${{ steps.head-commit-message.outputs.head_commit_message }}
      image_tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

      - name: Output the HEAD commit message
        id: head-commit-message
        run: |
          echo "head_commit_message=$(git log -1 --format=%s)" >> "$GITHUB_OUTPUT"

      - name: Display Repository Information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Pull Request head SHA: ${{ github.event.pull_request.head.sha || 'N/A' }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Event Head Commit Message: ${{ steps.head-commit-message.outputs.head_commit_message }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Github Workspace: ${{ github.workspace }}"

      - name: Run setup
        run: |
          bash setup.sh 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
      - name: Display metadata for Docker
        run: |
          echo "Docker Tags: ${{ steps.meta.outputs.tags }}"
          echo "Docker Labels: ${{ steps.meta.outputs.labels }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          pull: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-development:
    needs: build-and-push
    if: github.event_name == 'pull_request' && contains(needs.build-and-push.outputs.head_commit_message, '[deploy dev1]')
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run development deployment
        run: |
          docker run \
            -e DEPLOY_TARGET="development" \
            -e WORKSPACE="all" \
            -v $HOME/.events-platform-iac/config:/iac-config.yml \
            ${{ needs.build-and-push.outputs.image_tags }} \
            ./entrypoint.sh

  deploy-production:
    needs: build-and-push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run production deployment
        run: |
          docker run \
            -e DEPLOY_TARGET="production" \
            -e WORKSPACE="all" \
            -v $HOME/.events-platform-iac/config:/iac-config.yml \
            ${{ needs.build-and-push.outputs.image_tags }} \
            ./entrypoint.sh
